CREATE TABLE [dbo].[Placement]
(
	[RoomNo] NVARCHAR(10) NOT NULL,
	[ScannerId] NVARCHAR(100) NOT NULL,
	[PlacedDateTime] DATETIME NOT NULL, 
    [RemovedDateTime] DATETIME NULL,
	CONSTRAINT PK_PLACEMENT PRIMARY KEY (RoomNo, ScannerId, PlacedDateTime),
	CONSTRAINT FK_PLACEMENT_LOCATION FOREIGN KEY (RoomNo) REFERENCES Location,
	CONSTRAINT FK_PLACEMENT_SCANNER FOREIGN KEY (ScannerId) REFERENCES Scanner
)
