//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int CardNo { get; set; }
        public string ScannerId { get; set; }
        public System.DateTime TapDateTime { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Scanner Scanner { get; set; }
    }
}
