//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placement
    {
        public string RoomNo { get; set; }
        public string ScannerId { get; set; }
        public System.DateTime PlacedDateTime { get; set; }
        public Nullable<System.DateTime> RemovedDateTime { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Scanner Scanner { get; set; }
    }
}
