//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int SessionId { get; set; }
        public Nullable<System.DateTime> SessionDate { get; set; }
        public Nullable<int> CID { get; set; }
        public string RoomNo { get; set; }
    
        public virtual classgroup classgroup { get; set; }
        public virtual Location Location { get; set; }
    }
}
